services:
  web:
    build: .
    entrypoint: gunicorn -b unix:/tmp/gunicorn.sock -k uvicorn.workers.UvicornWorker --log-level warning main:app
    volumes:
     - ./app:/code
     - ./socket/:/tmp/
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./socket/:/tmp/
    depends_on:
      - web
  
